name: build adocs

on:
  push:
    branches:
    - main

env:
  PUBLIC_DIR: public
  REVEALJS_FILE: reveal.html
  HTML_FILE: index.html
  PDF_FILE: pdf.pdf
  PRESENTATION: readme.adoc

jobs:
  html_build:
    runs-on: ubuntu-latest
    name: Create HTML
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate HTML
      uses: lordsokaar/asciidoc-action@main
      with:
        program: "asciidoctor -r asciidoctor-diagram -D ${{ env.PUBLIC_DIR }} --backend=html5 -a linkcss -o ${{ env.HTML_FILE }} ${{ env.PRESENTATION }}"
    - uses: actions/upload-artifact@v4
      with:
        name: html
        path: ${{ env.PUBLIC_DIR }}/**
        retention-days: 1
    - uses: actions/upload-artifact@v4
      with:
        name: images
        path: images
        retention-days: 1
  pdf_build:
    runs-on: ubuntu-latest
    name: Create PDF
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate PDF
      uses: lordsokaar/asciidoc-action@main
      with:
        program: "asciidoctor -r asciidoctor-pdf -d book  -D ${{ env.PUBLIC_DIR }} -r asciidoctor-diagram -b pdf -o ${{ env.PDF_FILE }} ${{ env.PRESENTATION }}"
    - uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: ${{ env.PUBLIC_DIR }}/${{ env.PDF_FILE }}
        retention-days: 1
  deploy_page:
    runs-on: ubuntu-latest
    name: Deploy page
    needs: 
      - html_build
      - pdf_build
    steps:
      - name: Téléchargement du html
        uses: actions/download-artifact@v4
        with:
          name: html
      - name: Téléchargement des images
        uses: actions/download-artifact@v4
        with:
          name: images
      - name: Téléchargement du html
        uses: actions/download-artifact@v4
        with:
          name: pdf
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./

    # - name: Prepare publication
    #   run: mkdir public
    # - name: Build HTML
    #   id: htmlBuild
    #   uses: tonynv/asciidoctor-action@master
    #   with:
    #       program: "asciidoctor -D public --backend=html5 -o index.html readme.adoc"
    # - name: Build PDF
    #   id: pdfbuild
    #   uses: tonynv/asciidoctor-action@master
    #   with:
    #     program: "asciidoctor -D public -r asciidoctor-pdf -d book -r asciidoctor-diagram -b pdf -o pdf.pdf readme.adoc"
    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '14'
    # - name: Install npm dependencies
    #   run: npm install
    # - name: Create reveal
    #   run: npx asciidoctor-revealjs -o reveal.html -r asciidoctor-kroki readme.adoc
    # - name: Copy node
    #   run: cp -Rf node_modules public/
    # - name: Copy presentation
    #   run: cp reveal.html public/
    # - name: Copy images
    #   run: cp -Rf images public/
    # - name: Deploy docs to ghpages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     publish_dir: ./public