name: build adocs

on:
  push:
    branches:
    - main

env:
  PUBLIC_DIR: public
  REVEALJS_FILE: reveal.html
  HTML_FILE: index.html
  PDF_FILE: pdf.pdf
  PRESENTATION: readme.adoc

jobs:

  html_build:
    runs-on: ubuntu-latest
    name: Create HTML
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate HTML
      uses: lordsokaar/asciidoc-action@main
      with:
        program: "asciidoctor -r asciidoctor-diagram -D ${{ env.PUBLIC_DIR }} --backend=html5 -a linkcss -o ${{ env.HTML_FILE }} ${{ env.PRESENTATION }}"
    - name: HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: ${{ env.PUBLIC_DIR }}/**
        retention-days: 1
    - name: Images artifact
      uses: actions/upload-artifact@v4
      with:
        name: images
        path: images
        retention-days: 1

  pdf_build:
    runs-on: ubuntu-latest
    name: Create PDF
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate PDF
      uses: lordsokaar/asciidoc-action@main
      with:
        program: "asciidoctor -r asciidoctor-pdf -d book  -D ${{ env.PUBLIC_DIR }} -r asciidoctor-diagram -b pdf -o ${{ env.PDF_FILE }} ${{ env.PRESENTATION }}"
    - name: PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: ${{ env.PUBLIC_DIR }}/${{ env.PDF_FILE }}
        retention-days: 1

  reveal_build:
    runs-on: ubuntu-latest
    name: Create Reveal
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: npm install
      - name: Create reveal
        run: npx asciidoctor-revealjs -o ${{ env.REVEALJS_FILE }} -r asciidoctor-kroki ${{ env.PRESENTATION }}
      - name: node_modules artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules
          retention-days: 1
      - name: Revealjs artifact
        uses: actions/upload-artifact@v4
        with:
          name: revealjs
          path: ${{ env.REVEALJS_FILE }}
          retention-days: 1
  deploy_page:
    runs-on: ubuntu-latest
    name: Deploy page
    needs: 
      - html_build
      - pdf_build
      - reveal_build
    steps:
      - name: Téléchargement du html
        uses: actions/download-artifact@v4
        with:
          name: html
      - name: Téléchargement des images
        uses: actions/download-artifact@v4
        with:
          name: images
          path: ./images/
      - name: Téléchargement du html
        uses: actions/download-artifact@v4
        with:
          name: pdf
      - name: Téléchargement des node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: ./node_modules/
      - name: Téléchargement du revealjs
        uses: actions/download-artifact@v4
        with:
          name: revealjs
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./
